### ISSUE TITLE
リマインドするチャンネルを選べるようにする

### ISSUE THREAD

**Issue by koheitakahashi** [shibaaaa/reminder_bot#31]

**Comment by shibaaaa** [comment]
- チャンネルURLを入力させる
 - チャンネル名を入力させる
 - 詳細画面等にはURLを表示しない
 - 詳細画面等に入力したチャンネル名を表示させる

**Comment by shibaaaa** [comment]
## カラム追加

- webhook_url
    - string
    - not null
- channel_name
    - string
    - not null
