### ISSUE TITLE
📝リマインドがintervalならintervalの時間をリマインドの時刻に足して次回のリマインド時刻を設定する必要がありそう

### ISSUE THREAD

**Issue by shibaaaa** [shibaaaa/reminder_bot#7]
📝リマインドがintervalならintervalの時間をリマインドの時刻に足して次回のリマインド時刻を設定する必要がありそう

_Originally posted by @shibaaaa in https://github.com/shibaaaa/reminder_bot/issues/4#issuecomment-1061272719_

**Comment by koheitakahashi** [comment]
#11 で達成したので close
